package operations.core;

public enum RequestType {
	
	PORTAL_NETWORK_CONFIGURATION_REQUEST,
	CREATE_ANALYTICS_QUERY_FILTER_REQUEST,
	RUN_ANALYTICS_QUERY_FILTER_REQUEST,
	GET_ANALYTICS_HOME_DATASETS_REQUEST,
	GET_DASHBOARD_DATA_REQUEST,
	GET_ANALYTICS_DATA_REQUEST,
	CREATE_SURVEY_REQUEST
	
}
