package operations.core;

public enum ResponseType {
	
	PORTAL_NETWORK_CONFIGURATION_RESPONSE,
	CREATE_ANALYTICS_QUERY_FILTER_RESPONSE,
	RUN_ANALYTICS_QUERY_FILTER_RESPONSE,
	GET_ANALYTICS_HOME_DATASETS_RESPONSE
	
}
